version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: php:8.0-fpm
    container_name: awesome-app
    volumes:
      - .:/var/www/awesome
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - awesome-network

  nginx:
    image: nginx:1.23.4-alpine
    container_name: awesome-nginx
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/awesome
    networks:
      - awesome-network

  mysql:
    container_name: awesome-mysql
    image: mysql:8.0.33
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'temp123'
      MYSQL_DATABASE: awesome

    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/my.cnf
    networks:
      - awesome-network

networks:
  awesome-network:
    driver: bridge

volumes:
    mysql-volume:
        driver: local

