version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: php:8.0-fpm
    container_name: henbuk-app
    volumes:
      - .:/var/www/henbuk
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - henbuk-network

  nginx:
    image: nginx:1.23.4-alpine
    container_name: henbuk-nginx
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/henbuk
    networks:
      - henbuk-network

  mysql:
    container_name: henbuk-mysql
    image: mysql:8.0.33
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'temp123'
      MYSQL_USER: root
      MYSQL_DATABASE: henbuk

    volumes:
      - ./docker/data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/my.cnf
    networks:
      - henbuk-network

networks:
  henbuk-network:
    driver: bridge

